### ISSUE TITLE
Can't use latest release as pre-commit hook

### ISSUE THREAD

**Issue by kmiller96** [stefsmeets/nbcheckorder#2]
Hey @stefsmeets 👋

Tried bumping my pre-commit hook to `v0.1.3` but it failed. I think you need to make a new release 😄 

The exact error message:

```
[INFO] Initializing environment for https://github.com/stefsmeets/nbcheckorder/.
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', 'v0.1.3')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v0.1.3' did not match any file(s) known to git
    
Check the log at /home/xxx/.cache/pre-commit/pre-commit.log
```

My hook configuration:

```yaml
repos:
  - repo: https://github.com/stefsmeets/nbcheckorder/
    rev: v0.1.3
    hooks:
      - id: nbcheckorder
```

**Comment by stefsmeets** [comment]
> Tried bumping my pre-commit hook to `v0.1.3` but it failed. I think you need to make a new release 😄

That's it! Thanks for the heads-up, I forgot I had to do this 👍
Just checked, and it should work now.
